### ISSUE TITLE
Variable Groups: update documentation on how to use them

### ISSUE THREAD

**Issue by samiyaakhtar** [microsoft/spektate#9]
Following the instructions my app code pipeline didn't recognize the variable group (See #8). In order to get the pipeline to recognize my variable group I had to alter my azure-pipelines.yaml file. What I originally had for `variables`:

```
variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
```

Change I made to get the variable group to be recognized:

```
variables:
- group: container journey
- name: GOBIN  
  value: '$(GOPATH)/bin' # Go binaries path
- name: GOROOT 
  value: '/usr/local/go1.11' # Go installation path
- name: GOPATH
  value: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
- name: modulePath
  value: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code
```

I also had to update my HLD azure-pipelines.yaml file to add 
```
variables:
- group: container journey
```

I followed the instructions [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/variable-groups?view=azure-devops&tabs=yaml#use-a-variable-group).

Did you have the same issue? We should update the instructions if so.
